#!/usr/bin/env sh

# localectl set-x11-keymap 'latam,us,us(colemak)' '' '' 'grp:shifts_toggle,ctrl:nocaps,compose:menu,terminate:ctrl_alt_bksp'

# dot-prefixed files are skipped unless explicitly named
rcup -K config/zsh/{.zprofile,.zshenv,.zshrc,.zlogin,.zlogout,.zpreztorc}

# prezto has to be linked by hand, because it's skipped, and forcing
# rcup results in ignores SYMLINK_DIRS
if [ ! -h ${HOME}/.config/zsh/.zprezto ]; then
  ln -s ${HOME}/.dotfiles/config/zsh/.zprezto ${HOME}/.config/zsh/.zprezto
fi
