#!/usr/bin/env sh

# dot-prefixed files are skipped unless explicitly named
rcup -K config/zsh/{.zprofile,.zshenv,.zshrc,.zlogin,.zlogout,.zpreztorc}

# prezto has to be linked by hand, because it's skipped, and forcing
# rcup results in ignores SYMLINK_DIRS
if [ ! -h ${HOME}/.config/zsh/.zprezto ]; then
  ln -s ${HOME}/.dotfiles/config/zsh/.zprezto ${HOME}/.config/zsh/.zprezto
fi
