#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

# TODO: is there any specification about autostart directories/files?
#       is $XDG_CONFIG_HOME/autostart useful besides those .desktop?
function autostart {
  if [ -s "$XDG_CONFIG_HOME/autostart.sh" ]; then
    . "$XDG_CONFIG_HOME/autostart.sh"
  fi
}

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

userresources=$XDG_CONFIG_HOME/Xresources
usermodmap=$XDG_CONFIG_HOME/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

xsetroot -cursor_name left_ptr  # fix mouse cursor
feh --bg-scale ~/customize/wallpapers/wallpaper.jpg

autostart

case $1 in
  i3) exec i3 -V >> $XDG_CONFIG_HOME/i3/logs/log-$(date +'%F-%k-%M-%S') 2>&1;;
  gnome) exec gnome-session;;
  xmonad) exec xmonad;;
  bspswm) exec wm;;
  *) exec wm;; # to allow bspwm loop. See ~/.local/bin/wm
esac
